# Data Filter

In [1]:
import pandas as pd

In [2]:
path = "data.csv"

In [3]:
df = pd.read_csv(path)

## Filter Method

<ul>
    <li>DataFrame</li>
    <li>query</li>
    <li>loc</li>
</ul>

## DataFrame

使用方法df[filter_condition]

In [4]:
#equal filter1 = df['PTS'] > 26
filter1 = df.PTS > 26

In [5]:
df[filter1]

,#,Player,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF
0,1,James Harden,61,36.7,34.4,9.9,22.7,43.5,4.4,12.6,...,11.8,86.1,1.0,5.3,6.4,7.4,1.7,0.9,4.5,31.8
1,2,Bradley Beal,57,36.0,30.5,10.4,22.9,45.5,3.0,8.4,...,8.0,84.2,0.9,3.3,4.2,6.1,1.2,0.4,3.4,25.4
2,3,Giannis Antetokounmpo,57,30.9,29.6,10.9,20.0,54.7,1.5,4.8,...,10.0,63.3,2.3,11.5,13.7,5.8,1.0,1.0,3.7,34.8
3,4,Trae Young,60,35.3,29.6,9.1,20.8,43.7,3.4,9.5,...,9.3,86.0,0.5,3.7,4.3,9.3,1.1,0.1,4.8,26.6
4,5,Damian Lillard,58,36.9,28.9,9.2,20.0,45.7,3.9,9.9,...,7.6,88.8,0.5,3.8,4.3,7.8,1.0,0.4,2.9,27.8
5,6,Luka Doncic,54,33.3,28.7,9.5,20.6,46.1,2.9,9.1,...,9.1,75.2,1.3,8.0,9.3,8.7,1.1,0.2,4.2,30.4
6,7,Russell Westbrook,53,35.9,27.5,10.7,22.6,47.4,1.0,3.8,...,6.5,77.7,1.8,6.3,8.0,7.0,1.7,0.3,4.5,26.7
7,8,Kawhi Leonard,51,32.2,26.9,9.3,19.9,46.9,2.1,5.7,...,6.9,88.9,1.0,6.3,7.3,5.0,1.8,0.6,2.7,27.5
8,9,Anthony Davis,55,34.3,26.7,9.2,18.1,51.1,1.2,3.5,...,8.3,84.5,2.3,7.1,9.4,3.1,1.5,2.4,2.5,30.5
9,10,Devin Booker,62,36.1,26.1,8.8,18.0,48.7,2.0,5.6,...,7.1,91.6,0.4,3.7,4.2,6.6,0.7,0.3,3.9,24.0

如果需要多個篩選

In [6]:
filter2 = df.EFF > 30

In [7]:
df[filter1 &filter2]

,#,Player,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF
0,1,James Harden,61,36.7,34.4,9.9,22.7,43.5,4.4,12.6,...,11.8,86.1,1.0,5.3,6.4,7.4,1.7,0.9,4.5,31.8
2,3,Giannis Antetokounmpo,57,30.9,29.6,10.9,20.0,54.7,1.5,4.8,...,10.0,63.3,2.3,11.5,13.7,5.8,1.0,1.0,3.7,34.8
5,6,Luka Doncic,54,33.3,28.7,9.5,20.6,46.1,2.9,9.1,...,9.1,75.2,1.3,8.0,9.3,8.7,1.1,0.2,4.2,30.4
8,9,Anthony Davis,55,34.3,26.7,9.2,18.1,51.1,1.2,3.5,...,8.3,84.5,2.3,7.1,9.4,3.1,1.5,2.4,2.5,30.5

也可以直接寫在裡面

In [8]:
df[(df.PTS > 26) & (df['EFF'] > 30)]

,#,Player,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF
0,1,James Harden,61,36.7,34.4,9.9,22.7,43.5,4.4,12.6,...,11.8,86.1,1.0,5.3,6.4,7.4,1.7,0.9,4.5,31.8
2,3,Giannis Antetokounmpo,57,30.9,29.6,10.9,20.0,54.7,1.5,4.8,...,10.0,63.3,2.3,11.5,13.7,5.8,1.0,1.0,3.7,34.8
5,6,Luka Doncic,54,33.3,28.7,9.5,20.6,46.1,2.9,9.1,...,9.1,75.2,1.3,8.0,9.3,8.7,1.1,0.2,4.2,30.4
8,9,Anthony Davis,55,34.3,26.7,9.2,18.1,51.1,1.2,3.5,...,8.3,84.5,2.3,7.1,9.4,3.1,1.5,2.4,2.5,30.5

也可以使用lambda 表示是當作filter condition

In [9]:
df[lambda x : x['EFF'] >30]

,#,Player,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF
0,1,James Harden,61,36.7,34.4,9.9,22.7,43.5,4.4,12.6,...,11.8,86.1,1.0,5.3,6.4,7.4,1.7,0.9,4.5,31.8
2,3,Giannis Antetokounmpo,57,30.9,29.6,10.9,20.0,54.7,1.5,4.8,...,10.0,63.3,2.3,11.5,13.7,5.8,1.0,1.0,3.7,34.8
5,6,Luka Doncic,54,33.3,28.7,9.5,20.6,46.1,2.9,9.1,...,9.1,75.2,1.3,8.0,9.3,8.7,1.1,0.2,4.2,30.4
8,9,Anthony Davis,55,34.3,26.7,9.2,18.1,51.1,1.2,3.5,...,8.3,84.5,2.3,7.1,9.4,3.1,1.5,2.4,2.5,30.5
10,11,LeBron James,60,34.9,25.7,9.8,19.6,49.8,2.2,6.4,...,5.7,69.7,1.0,6.9,7.9,10.6,1.2,0.5,4.0,30.4

In [10]:
df[ df.apply(lambda x : x['EFF'] >30 and x['PTS'] >26,axis = 1)]

,#,Player,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF
0,1,James Harden,61,36.7,34.4,9.9,22.7,43.5,4.4,12.6,...,11.8,86.1,1.0,5.3,6.4,7.4,1.7,0.9,4.5,31.8
2,3,Giannis Antetokounmpo,57,30.9,29.6,10.9,20.0,54.7,1.5,4.8,...,10.0,63.3,2.3,11.5,13.7,5.8,1.0,1.0,3.7,34.8
5,6,Luka Doncic,54,33.3,28.7,9.5,20.6,46.1,2.9,9.1,...,9.1,75.2,1.3,8.0,9.3,8.7,1.1,0.2,4.2,30.4
8,9,Anthony Davis,55,34.3,26.7,9.2,18.1,51.1,1.2,3.5,...,8.3,84.5,2.3,7.1,9.4,3.1,1.5,2.4,2.5,30.5

也可寫成function,如果需要自訂複雜的過濾條件建議寫成function

In [11]:
def filter_condition(x):
    return  x['EFF'] >30 and x['PTS'] >26

In [12]:
df[df.apply(lambda x : filter_condition(x),axis = 1)]

,#,Player,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF
0,1,James Harden,61,36.7,34.4,9.9,22.7,43.5,4.4,12.6,...,11.8,86.1,1.0,5.3,6.4,7.4,1.7,0.9,4.5,31.8
2,3,Giannis Antetokounmpo,57,30.9,29.6,10.9,20.0,54.7,1.5,4.8,...,10.0,63.3,2.3,11.5,13.7,5.8,1.0,1.0,3.7,34.8
5,6,Luka Doncic,54,33.3,28.7,9.5,20.6,46.1,2.9,9.1,...,9.1,75.2,1.3,8.0,9.3,8.7,1.1,0.2,4.2,30.4
8,9,Anthony Davis,55,34.3,26.7,9.2,18.1,51.1,1.2,3.5,...,8.3,84.5,2.3,7.1,9.4,3.1,1.5,2.4,2.5,30.5

## Query

df.query(expr),expr為string

<strong>Note:如果欄位有空白用``夾住</strong>

In [13]:
df.query('PTS > 26 & EFF > 30')

,#,Player,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF
0,1,James Harden,61,36.7,34.4,9.9,22.7,43.5,4.4,12.6,...,11.8,86.1,1.0,5.3,6.4,7.4,1.7,0.9,4.5,31.8
2,3,Giannis Antetokounmpo,57,30.9,29.6,10.9,20.0,54.7,1.5,4.8,...,10.0,63.3,2.3,11.5,13.7,5.8,1.0,1.0,3.7,34.8
5,6,Luka Doncic,54,33.3,28.7,9.5,20.6,46.1,2.9,9.1,...,9.1,75.2,1.3,8.0,9.3,8.7,1.1,0.2,4.2,30.4
8,9,Anthony Davis,55,34.3,26.7,9.2,18.1,51.1,1.2,3.5,...,8.3,84.5,2.3,7.1,9.4,3.1,1.5,2.4,2.5,30.5

In [14]:
df.query('EFF > `PTS`+ 5')

,#,Player,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF
2,3,Giannis Antetokounmpo,57,30.9,29.6,10.9,20.0,54.7,1.5,4.8,...,10.0,63.3,2.3,11.5,13.7,5.8,1.0,1.0,3.7,34.8
28,29,Nikola Jokic,65,32.3,20.2,7.9,14.9,52.8,1.1,3.5,...,4.1,81.3,2.4,7.8,10.2,6.9,1.2,0.7,3.1,28.2
33,34,Nikola Vucevic,54,32.6,19.5,7.9,16.9,47.0,1.5,4.6,...,2.7,78.1,2.4,8.6,11.0,3.7,0.9,0.9,1.4,25.0
46,47,Domantas Sabonis,62,34.8,18.5,7.4,13.7,54.0,0.3,1.1,...,4.8,72.3,3.0,9.4,12.4,5.0,0.8,0.5,2.7,26.8

## loc

跟 dataframe 使用一樣

In [15]:
df.loc[(df.PTS > 26) & (df.EFF > 30)]

,#,Player,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF
0,1,James Harden,61,36.7,34.4,9.9,22.7,43.5,4.4,12.6,...,11.8,86.1,1.0,5.3,6.4,7.4,1.7,0.9,4.5,31.8
2,3,Giannis Antetokounmpo,57,30.9,29.6,10.9,20.0,54.7,1.5,4.8,...,10.0,63.3,2.3,11.5,13.7,5.8,1.0,1.0,3.7,34.8
5,6,Luka Doncic,54,33.3,28.7,9.5,20.6,46.1,2.9,9.1,...,9.1,75.2,1.3,8.0,9.3,8.7,1.1,0.2,4.2,30.4
8,9,Anthony Davis,55,34.3,26.7,9.2,18.1,51.1,1.2,3.5,...,8.3,84.5,2.3,7.1,9.4,3.1,1.5,2.4,2.5,30.5

In [16]:
df.loc[(df['PTS'] > 26) & (df.EFF > 30)]

,#,Player,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF
0,1,James Harden,61,36.7,34.4,9.9,22.7,43.5,4.4,12.6,...,11.8,86.1,1.0,5.3,6.4,7.4,1.7,0.9,4.5,31.8
2,3,Giannis Antetokounmpo,57,30.9,29.6,10.9,20.0,54.7,1.5,4.8,...,10.0,63.3,2.3,11.5,13.7,5.8,1.0,1.0,3.7,34.8
5,6,Luka Doncic,54,33.3,28.7,9.5,20.6,46.1,2.9,9.1,...,9.1,75.2,1.3,8.0,9.3,8.7,1.1,0.2,4.2,30.4
8,9,Anthony Davis,55,34.3,26.7,9.2,18.1,51.1,1.2,3.5,...,8.3,84.5,2.3,7.1,9.4,3.1,1.5,2.4,2.5,30.5

一樣可以搭配lambda

In [17]:
df.loc[ lambda x : x['EFF'] >30]

,#,Player,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF
0,1,James Harden,61,36.7,34.4,9.9,22.7,43.5,4.4,12.6,...,11.8,86.1,1.0,5.3,6.4,7.4,1.7,0.9,4.5,31.8
2,3,Giannis Antetokounmpo,57,30.9,29.6,10.9,20.0,54.7,1.5,4.8,...,10.0,63.3,2.3,11.5,13.7,5.8,1.0,1.0,3.7,34.8
5,6,Luka Doncic,54,33.3,28.7,9.5,20.6,46.1,2.9,9.1,...,9.1,75.2,1.3,8.0,9.3,8.7,1.1,0.2,4.2,30.4
8,9,Anthony Davis,55,34.3,26.7,9.2,18.1,51.1,1.2,3.5,...,8.3,84.5,2.3,7.1,9.4,3.1,1.5,2.4,2.5,30.5
10,11,LeBron James,60,34.9,25.7,9.8,19.6,49.8,2.2,6.4,...,5.7,69.7,1.0,6.9,7.9,10.6,1.2,0.5,4.0,30.4

## Filter with Operator

前面都使用基本的運算式,pandas 還有提供其他的可以使用

### df[col_name].lt (lt,le,gt,ge,eq)

In [18]:
# filter greater equal 30 
df[df["EFF"].ge(30)]

,#,Player,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF
0,1,James Harden,61,36.7,34.4,9.9,22.7,43.5,4.4,12.6,...,11.8,86.1,1.0,5.3,6.4,7.4,1.7,0.9,4.5,31.8
2,3,Giannis Antetokounmpo,57,30.9,29.6,10.9,20.0,54.7,1.5,4.8,...,10.0,63.3,2.3,11.5,13.7,5.8,1.0,1.0,3.7,34.8
5,6,Luka Doncic,54,33.3,28.7,9.5,20.6,46.1,2.9,9.1,...,9.1,75.2,1.3,8.0,9.3,8.7,1.1,0.2,4.2,30.4
8,9,Anthony Davis,55,34.3,26.7,9.2,18.1,51.1,1.2,3.5,...,8.3,84.5,2.3,7.1,9.4,3.1,1.5,2.4,2.5,30.5
10,11,LeBron James,60,34.9,25.7,9.8,19.6,49.8,2.2,6.4,...,5.7,69.7,1.0,6.9,7.9,10.6,1.2,0.5,4.0,30.4

### df[col_name].between(a,b)

In [19]:
df[df["GP"].between(55,60)]

,#,Player,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF
1,2,Bradley Beal,57,36.0,30.5,10.4,22.9,45.5,3.0,8.4,...,8.0,84.2,0.9,3.3,4.2,6.1,1.2,0.4,3.4,25.4
2,3,Giannis Antetokounmpo,57,30.9,29.6,10.9,20.0,54.7,1.5,4.8,...,10.0,63.3,2.3,11.5,13.7,5.8,1.0,1.0,3.7,34.8
3,4,Trae Young,60,35.3,29.6,9.1,20.8,43.7,3.4,9.5,...,9.3,86.0,0.5,3.7,4.3,9.3,1.1,0.1,4.8,26.6
4,5,Damian Lillard,58,36.9,28.9,9.2,20.0,45.7,3.9,9.9,...,7.6,88.8,0.5,3.8,4.3,7.8,1.0,0.4,2.9,27.8
8,9,Anthony Davis,55,34.3,26.7,9.2,18.1,51.1,1.2,3.5,...,8.3,84.5,2.3,7.1,9.4,3.1,1.5,2.4,2.5,30.5
10,11,LeBron James,60,34.9,25.7,9.8,19.6,49.8,2.2,6.4,...,5.7,69.7,1.0,6.9,7.9,10.6,1.2,0.5,4.0,30.4
11,12,Zach LaVine,60,34.8,25.5,9.0,20.0,45.0,3.1,8.1,...,5.6,80.2,0.7,4.1,4.8,4.2,1.5,0.5,3.4,21.0
12,13,Brandon Ingram,56,34.3,24.3,8.4,18.0,46.6,2.4,6.3,...,5.9,85.8,0.9,5.4,6.3,4.3,1.0,0.7,3.1,22.9
15,16,Jayson Tatum,59,34.6,23.6,8.5,18.9,44.8,2.8,7.1,...,4.7,80.6,1.0,6.1,7.1,2.9,1.4,0.9,2.2,22.3
21,22,Khris Middleton,55,30.1,21.1,7.7,15.5,49.9,2.4,5.8,...,3.6,90.8,0.7,5.5,6.2,4.1,0.9,0.1,2.1,22.3
31,32,Jrue Holiday,55,34.9,19.6,7.7,16.9,45.2,2.1,5.9,...,3.1,70.0,1.3,3.6,4.9,6.9,1.7,0.8,2.9,20.7
37,38,Danilo Gallinari,55,30.7,19.2,6.0,13.6,43.9,3.0,7.3,...,4.8,88.6,0.6,4.9,5.5,2.1,0.7,0.1,1.3,18.1
41,42,Jamal Murray,55,32.8,18.8,7.0,15.4,45.5,1.9,5.5,...,3.2,89.3,0.8,3.2,3.9,4.8,1.2,0.3,2.3,18.0
43,44,Kelly Oubre Jr.,56,34.5,18.7,6.7,14.8,45.2,1.9,5.5,...,4.4,78.0,1.2,5.3,6.4,1.5,1.3,0.7,1.5,18.1
44,45,Lou Williams,60,29.3,18.7,6.1,14.7,41.6,1.8,4.9,...,5.4,86.3,0.5,2.6,3.1,5.7,0.7,0.2,2.9,16.1

### df[col_name].isnull()

### df[col_name].notnull()

### df[col_name].isin(array)

In [20]:
df[df["Player"].isin(['LeBron James','Anthony Davis'])]

,#,Player,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF
8,9,Anthony Davis,55,34.3,26.7,9.2,18.1,51.1,1.2,3.5,...,8.3,84.5,2.3,7.1,9.4,3.1,1.5,2.4,2.5,30.5
10,11,LeBron James,60,34.9,25.7,9.8,19.6,49.8,2.2,6.4,...,5.7,69.7,1.0,6.9,7.9,10.6,1.2,0.5,4.0,30.4

### df[col_name].str.contains(str, na=False)

In [21]:
df[df["Player"].str.contains("James", na=False)]

,#,Player,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF
0,1,James Harden,61,36.7,34.4,9.9,22.7,43.5,4.4,12.6,...,11.8,86.1,1.0,5.3,6.4,7.4,1.7,0.9,4.5,31.8
10,11,LeBron James,60,34.9,25.7,9.8,19.6,49.8,2.2,6.4,...,5.7,69.7,1.0,6.9,7.9,10.6,1.2,0.5,4.0,30.4

使用 |　多個條件篩選

In [22]:
df[df["Player"].str.contains("James|Davis|Luka", na=False)]

,#,Player,GP,MIN,PTS,FGM,FGA,FG%,3PM,3PA,...,FTA,FT%,OREB,DREB,REB,AST,STL,BLK,TOV,EFF
0,1,James Harden,61,36.7,34.4,9.9,22.7,43.5,4.4,12.6,...,11.8,86.1,1.0,5.3,6.4,7.4,1.7,0.9,4.5,31.8
5,6,Luka Doncic,54,33.3,28.7,9.5,20.6,46.1,2.9,9.1,...,9.1,75.2,1.3,8.0,9.3,8.7,1.1,0.2,4.2,30.4
8,9,Anthony Davis,55,34.3,26.7,9.2,18.1,51.1,1.2,3.5,...,8.3,84.5,2.3,7.1,9.4,3.1,1.5,2.4,2.5,30.5
10,11,LeBron James,60,34.9,25.7,9.8,19.6,49.8,2.2,6.4,...,5.7,69.7,1.0,6.9,7.9,10.6,1.2,0.5,4.0,30.4